### ISSUE TITLE
Tests for audio player

### ISSUE THREAD

**Issue by infojunkie** [0xfe/vextab#32]
It would be great to have tests that show the MIDI player functionality.

**Comment by spencerhitch** [comment]
@timaschew I'm curious about this as well. Trying to get player running locally myself. Do you remember what steps you took?

As of right now I've:
* modified player.coffee to module.export itself
* modified artist.coffee to require player.coffee and instantiate a new player when @customizations.player = "true"
* now I've added midi as a dependency using `npm install mudcube/MIDI.js --save` and I'm trying to require 'midi' in player.coffee but it's not finding it

Is this the right track? I'd love to know how you approached this

**Comment by timaschew** [comment]
> `npm install mudcube/MIDI.js --save`

This doesn't work, this part of midisjs is really shitty, see 
https://github.com/mudcube/MIDI.js/issues/24#issuecomment-131570903

I'm not sure anymore and I deleted the branch because I switched to another library.
I'm also using vexflow and not vextab now.

But I remember MIDI.js was the issue because it's not a valid CommonJS module. You need load all the files (dependencies of MIDI.js) by hand.

Here is the most simple example with midisjs, you should see what files you need:
https://github.com/mudcube/MIDI.js/blob/master/examples/Basic.html
you can also run this example with rawgit: https://rawgit.com/mudcube/MIDI.js/master/examples/Basic.html

**Comment by spencerhitch** [comment]
Ah bummer,

`npm install mudcube/MIDI.js` would be really nice :(

Thanks for the response

I'll see what I can do based on the Basic.html example

**Comment by spencerhitch** [comment]
Ok I got player in `playground` working by modifying a few things I'll go ahead and detail my steps to getting it working for posterity

1. To run paper.js you'll need to have cairo installed. On osx `brew install cairo` should handle this
2. Add paper.js to the node dependencies and install it with `npm install paper --save`
3. Make sure `player.coffee` has access to paper by adding the line `paper = require 'paper'` next to the other `require` statements
3. Make `player.coffee` available by adding the line `module.exports = Vex.Flow.Player` somewhere in the file
4. Make the `main.coffee` module export the Player by adding `Player = require './player.coffee'` to the requires and adding `Player: Player` to the `module.exports` list.
5. Because [MIDI.js](https://github.com/mudcube/MIDI.js) is required but is not packaged for npm functionality, it's easiest to just include the necessary files in your html. To know which ones to include look at the [Basic.html](https://github.com/mudcube/MIDI.js/blob/master/examples/Basic.html) example
6. Grab a pre-rendered soundfont from [gleitz](https://github.com/gleitz/midi-js-soundfonts) and store it in a `soundfont/` directory wherever `player.coffee`'s `options.soundfont_url` points
7. Instantiate your player in `tests/playground.js` by adding `Player = vextab.Player;` right after `Renderer = ...` and `player = new Player(artist);` right after `artist = new Artist(...`
8. Before you test run `npm start` to make sure you still pass all the tests then build `build/playground.js` with `grunt playground`
9. You're gonna need to run a server using something like `python -m SimpleHTTPServer` to avoid cross-site scripting errors that will be thrown when trying to access the soundfont. You can then access playground via `localhost:8000/tests/playground.html`

**Comment by 0xfe** [comment]
Thanks for these instructions. Do you mind adding them to the VexTab wiki?

On Thu, Jan 21, 2016 at 2:13 PM, Spencer Hitchcock <notifications@github.com
> wrote:

> Ok I got player in playground working by modifying a few things I'll go
> ahead and detail my steps to getting it working for posterity
>
>    1. To run paper.js you'll need to have cairo installed. On osx brew
>    install cairo should handle this
>    2. Add paper.js to the node dependencies and install it with npm
>    install paper --save
>    3. Make sure player.coffee has access to paper by adding the line paper
>    = require 'paper' next to the other require statements
>    4. Make player.coffee available by adding the line module.exports =
>    Vex.Flow.Player somewhere in the file
>    5. Make the main.coffee module export the Player by adding Player =
>    require './player.coffee' to the requires and adding Player: Player to
>    the module.exports list.
>    6. Because MIDI.js <https://github.com/mudcube/MIDI.js> is required
>    but is not packaged for npm functionality, it's easiest to just include the
>    necessary files in your html. To know which ones to include look at the
>    Basic.html
>    <https://github.com/mudcube/MIDI.js/blob/master/examples/Basic.html>
>    example
>    7. Grab a pre-rendered soundfont from gleitz
>    <https://github.com/gleitz/midi-js-soundfonts> and store it in a
>    soundfont/ directory wherever player.coffee's options.soundfont_url
>    points
>    8. Instantiate your player in tests/playground.js by adding Player =
>    vextab.Player; right after Renderer = ... and player = new
>    Player(artist); right after artist = new Artist(...
>    9. Before you test run npm start to make sure you still pass all the
>    tests then build build/playground.js with grunt playground
>    10. You're gonna need to run a server using something like python -m
>    SimpleHTTPServer to avoid cross-site scripting errors that will be
>    thrown when trying to access the soundfont. You can then access playground
>    via localhost:8000/tests/playground.html
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/0xfe/vextab/issues/32#issuecomment-173677963>.
>



-- 
Mohit Muthanna [mohit (at) muthanna (uhuh) com]

**Comment by spencerhitch** [comment]
Do you want me to add it to the Vextab Wiki, which is currently empty, or do you mean the readme or the vexflow wiki?

**Comment by 0xfe** [comment]
Okay, I didn't realize that the VexTab wiki was empty. I'll go ahead and
set it up.

On Thu, Jan 21, 2016 at 6:24 PM, Spencer Hitchcock <notifications@github.com
> wrote:

> Do you want me to add it to the Vextab Wiki, which is currently empty, or
> do you mean the readme or the vexflow wiki?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/0xfe/vextab/issues/32#issuecomment-173748133>.
>



-- 
Mohit Muthanna [mohit (at) muthanna (uhuh) com]

**Comment by masterofdaemon** [comment]
can i get repo with working example? I even can build it:
Running "browserify:playground" (browserify) task
>> Error: Cannot find module 'vextab' from '/Users/serg/GitHub/vextab/tests'
Warning: Error running grunt-browserify. Use --force to continue.

**Comment by masterofdaemon** [comment]
Can i get working repo? Too many changes...

**Comment by masterofdaemon** [comment]
it's freeze on "Loading instruments..." i can make a repo of my example but i think it's bug in new version of vextab, http://my.vexflow.com/articles/40 here, it's the same issue here

**Comment by masterofdaemon** [comment]
Warning:  Unsorted keys in note will be sorted. See https://github.com/0xfe/vexflow/issues/104 for details. Error
